### ISSUE TITLE
Symbol's function definition is void: chinese-word-cjk-string-p

### ISSUE THREAD

**Issue by zilongshanren** [xuchunyang/chinese-word-at-point.el#2]
After upgrade to the latest version of `chinese-word-at-point`， it failed when use youdao dictionary package.

I have searched all of your code, the `chinese-word-at-point` function is missing.

And in release 0.2.1, it is even missing there.

**Comment by xuchunyang** [comment]
Thanks for report this.  I committed without testing, it is a bad habit.
