### ISSUE TITLE
关于新增"thing"的一点疑问

### ISSUE THREAD

**Issue by lujun9972** [xuchunyang/chinese-word-at-point.el#3]
根据thingatpt.el中的说明,添加"thing"的方式似乎是为"thing"设置forward-op,begnning-op和end-op这三个属性值设置相应的位移函数.

``` elisp
;; Special cases are allowed for using properties associated with the named
;; "thing":
;;
;;   forward-op     Function to call to skip forward over a "thing" (or
;;                      with a negative argument, backward).
;;
;;   beginning-op   Function to call to skip to the beginning of a "thing".
;;   end-op     Function to call to skip to the end of a "thing".

```

但是,看您的代码中是直接为"thing"的bounds-of-thing-at-point属性设置个表示范围的函数就OK了?

我看的是emacs25.1.50中的源代码,不知道会不会是定义"thing"的方式改变了?

**Comment by xuchunyang** [comment]
> 根据thingatpt.el中的说明,添加"thing"的方式似乎是为"thing"设置forward-op,begnning-op和end-op这三个属性值设置相应的位移函数.

看起来确实没错，我写 chinese-word-at-point 的时候应该压根就没搞明白怎么正确地添加新的 thing，估计得需要看懂 thingatpt.el 是如何实现的。

> 但是,看您的代码中是直接为"thing"的bounds-of-thing-at-point属性设置个表示范围的函数就OK了?

在只用到 (thing-at-point 'chinese-word) 这一个的话（只需要看下 thing-at-point 这个函数的定义就能明白了）就没问题，但是至于 thingatpt.el 的其它三个 API：beginning-of-thing，end-of-thing 和 forward-thing 估计就不行了。

**Comment by lujun9972** [comment]
嗯，我看了下thing-at-point的定义，确实会先检查"thing"的bounds-of-thing-at-point属性。多谢~
